/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 08-nov.-2022 9:05:50 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_AsignaturaEstudiante_Estudiante]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [AsignaturaEstudiante] DROP CONSTRAINT [FK_AsignaturaEstudiante_Estudiante]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_AsignaturaEstudiante_Asignatura]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [AsignaturaEstudiante] DROP CONSTRAINT [FK_AsignaturaEstudiante_Asignatura]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Asignatura]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Asignatura]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[AsignaturaEstudiante]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [AsignaturaEstudiante]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estudiante]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estudiante]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

/* Create Tables */

CREATE TABLE [Asignatura]
(
	[AsignaturaID] int NOT NULL IDENTITY (1, 1),
	[Nombreasig] nvarchar(50) NULL,
	[Estadoasig] int NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [AsignaturaEstudiante]
(
	[idDetalle] int NOT NULL,
	[EstudianteID] int NOT NULL,
	[AsignaturaID] int NOT NULL,
	[Nota] int NOT NULL
)
GO

CREATE TABLE [Estudiante]
(
	[EstudianteID] int NOT NULL IDENTITY (1, 1),
	[NombreEst] nvarchar(30) NULL,
	[ApellidosEst] nvarchar(30) NULL,
	[Ciudadest] nvarchar(30) NULL,
	[Direccion] nvarchar(100) NULL,
	[Carrera] nvarchar(30) NULL
)
GO

CREATE TABLE [Usuario]
(
	[UsuarioID] int NOT NULL IDENTITY (1, 1),
	[Username] nvarchar(30) NOT NULL,
	[Userpw] nvarchar(30) NOT NULL,
	[Nombres] nvarchar(30) NOT NULL,
	[Apellidos] nvarchar(30) NOT NULL,
	[Email] nvarchar(100) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Asignatura] 
 ADD CONSTRAINT [PK_Asignatura]
	PRIMARY KEY CLUSTERED ([AsignaturaID] ASC)
GO

ALTER TABLE [AsignaturaEstudiante] 
 ADD CONSTRAINT [PK_AsignaturaEstudiante]
	PRIMARY KEY CLUSTERED ([idDetalle] ASC)
GO

ALTER TABLE [Estudiante] 
 ADD CONSTRAINT [PK_Estudiante]
	PRIMARY KEY CLUSTERED ([EstudianteID] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([UsuarioID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [AsignaturaEstudiante] ADD CONSTRAINT [FK_AsignaturaEstudiante_Estudiante]
	FOREIGN KEY ([EstudianteID]) REFERENCES [Estudiante] ([EstudianteID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [AsignaturaEstudiante] ADD CONSTRAINT [FK_AsignaturaEstudiante_Asignatura]
	FOREIGN KEY ([AsignaturaID]) REFERENCES [Asignatura] ([AsignaturaID]) ON DELETE No Action ON UPDATE No Action
GO
